version: '3'
services:
  fluent:
    # image: fluent/fluentd:latest
    build: ${PWD}/fluent_d/
    container_name: fluent
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ${PWD}/conf:/fluentd/etc
      - ${PWD}/log:/fluentd/log
    depends_on:
      - es
    networks:
      fluentd-elastic-stack-ver0.0.1:
        ipv4_address: 11.254.249.90
    links:
      - "es"
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 11.254.249.90:24224
        tag: nginx.hello
        fluentd-async-connect: "true"
    depends_on:
      - fluent
    networks:
      fluentd-elastic-stack-ver0.0.1:
        ipv4_address: 11.254.249.89

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - node.master=true
      - node.data=true
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - ${PWD}/es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 11.254.249.86:24225
        tag: elastic.hello
        fluentd-async-connect: "true"
    depends_on:
      - patch
    networks:
      fluentd-elastic-stack-ver0.0.1:
        ipv4_address: 11.254.249.88
  
  patch:
    image: fluent/fluentd:latest
    container_name: patch
    ports:
      - "24225:24225"
      - "24225:24225/udp"
    volumes:
      - ${PWD}/patch/conf:/fluentd/etc
      - ${PWD}/patch/log:/fluentd/log
    
    networks:
      fluentd-elastic-stack-ver0.0.1:
        ipv4_address: 11.254.249.86
    
    

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      fluentd-elastic-stack-ver0.0.1:
        ipv4_address: 11.254.249.87

volumes:
  es_data:
    driver: local


networks:
  fluentd-elastic-stack-ver0.0.1:
    ipam:
      driver: default
      config:
        - subnet: 11.254.249.0/24